export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Verify } from './Verify'
export { default as Dashboard } from './Dashboard'
export { default as ProtectedRoute } from './ProtectedRoute'
export { default as Posts } from './Posts'
export { default as Suggestions } from './Suggestions'
export { default as Account } from './Account'